name: Generating Artifacts
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react-demo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependencies-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react-demo
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependencies-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ./second-action-react-demo/dist
      - name: Current Working Directory
        run: pwd

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    # defaults:
      # run:
      #   working-directory: second-action-react-demo
    steps:
      - name: Current Working Directory
        run: pwd
      - name: List files
        run: ls
      - name: Current Working Directory
        run: pwd
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Deploy
        run: echo "Deploying..."
          
    