name: Generating Artifacts
on:
  push:
    branches:
      - main
jobs:
  
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react-demo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react-demo
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./second-action-react-demo
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying..."
          
    