name: Output information
on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "The event that triggered this action was ${{ github.event_name }}"
      
      - name: Output the repository name
        run: echo "The repository name is ${{ github.repository }}"
